### ISSUE TITLE
grafana_api_client support user manager ?

### ISSUE THREAD

**Issue by rfyiamcool** [htch/grafana_api_client#4]
grafana_api_client support user manager ?

same as grafana http api action 

```
Add a new user to the actual organisation
POST /api/org/users

Updates the given user
PATCH /api/org/users/:userId

Delete user in actual organisation
DELETE /api/org/users/:userId
```

**Comment by jcmcken** [comment]
Not the author, but it should work. You'll have to use ``getattr`` though, e.g.

```python
getattr(client.org.users, "15").delete()
```

It would be nice if there were some convenience function for calling URLs like this, e.g.

```python
client("api.org.users.4").delete()
```

**Comment by jcmcken** [comment]
Oh, you should also be able to address endpoints like this as well:

```python
client.org.users["15"].delete()
```
