### ISSUE TITLE
Debianization

### ISSUE THREAD

**Issue by amarao** [htch/grafana_api_client#9]
Hello.

I've done a basic debianization (ability to build 'deb' package from source) for grafana_api_client. It should be kept in 'debian' branch.

This repo has no 'debian' branch so I couldn't send pull request, but I will really appreciate if you accept changes.

They are here: https://github.com/amarao/grafana_api_client/tree/debian

**Comment by htch** [comment]
@amarao Hello. Sure I'm happy to merge this in, but why do you say it should be kept in "debian" branch?

**Comment by amarao** [comment]
I heard from debian guys (real maintainers) that they really dislike if someone includes 'debian' folder in their tarballs (upstream distribution). When maintainer adopt software it need some space for tweaks and changes in rules, control files, etc. Normally they are stored in 'debian' folder, but if this folder is occupied, they will have big problems separating their 'debian' part from upstream.

So their advice was to keep 'debian' folder in a separate branch

**Comment by htch** [comment]
Thanks for the explanation. Created "debian" branch for you to make a PR.

**Comment by amarao** [comment]
Thank you!
